services:
  db:
    image: postgres:16-alpine
    container_name: distincthomes-db
    environment:
      POSTGRES_USER: distincthomes
      POSTGRES_PASSWORD: distincthomes
      POSTGRES_DB: distincthomes
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
